# Generated by Django 4.0.5 on 2022-06-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomerFeedback', '0002_delete_userbankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=10)),
                ('comments', models.TextField(max_length=200)),
            ],
        ),
    ]
