# Generated by Django 4.0.5 on 2022-06-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFeedback', '0005_alter_customerfeedback_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
