# Generated by Django 4.0.5 on 2022-06-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFeedback', '0006_alter_customerfeedback_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='comments',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
