# Generated by Django 4.0.5 on 2022-06-12 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFeedback', '0007_alter_customerfeedback_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerfeedback',
            old_name='phone_no',
            new_name='phone_No',
        ),
    ]
