# Generated by Django 4.0.4 on 2022-06-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_customer_aadhar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='default',
        ),
    ]
