# Generated by Django 4.0.5 on 2022-06-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('emailid', models.EmailField(max_length=30)),
                ('phone_noo', models.CharField(max_length=10)),
            ],
        ),
    ]
