# Generated by Django 4.0.5 on 2022-06-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_services_i_agree_alter_services_email_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='i_Agree',
            new_name='i_Agree_to_the_Terms_and_Conditions',
        ),
    ]
