# Generated by Django 4.0.5 on 2022-06-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=30)),
                ('last_Name', models.CharField(max_length=30)),
                ('email_Address', models.EmailField(max_length=30)),
                ('phone_Number', models.CharField(max_length=10)),
                ('query_Title', models.CharField(choices=[('Registration Process', 'Registration Process'), ('Dashboard', 'Dashboard'), ('Account', 'Account'), ('Transfer', 'Transfer'), ('My Profile', 'My Profile'), ('Banking Services', 'Banking Services'), ('Customer Feedback Form', 'Customer Feedback Form'), ('Customer Query Form', 'Customer Query Form'), ('Contact Us', 'Contact Us')], max_length=30)),
                ('query_Description', models.TextField(max_length=500)),
            ],
        ),
    ]
