# Generated by Django 4.0.4 on 2022-05-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transfer', '0004_transfermoney_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfermoney',
            name='name',
        ),
        migrations.AddField(
            model_name='transfermoney',
            name='interset',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
