# Generated by Django 4.0.4 on 2022-05-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transfer', '0005_remove_transfermoney_name_transfermoney_interset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfermoney',
            name='interset',
        ),
    ]
