# Generated by Django 4.0.4 on 2022-05-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transfer', '0006_remove_transfermoney_interset'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfermoney',
            name='status',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
