# Generated by Django 4.0.4 on 2022-05-15 14:40

import Account.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('Account_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('period', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('account_no', models.BigIntegerField(blank=True, unique=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('interest_start_date', models.DateField(auto_now_add=True, help_text='The month number that interest calculation will start from')),
                ('initial_deposit_date', models.DateField(auto_now_add=True)),
                ('Referrence_Number', models.CharField(blank=True, default=Account.utils.create_new_ref_number, editable=False, max_length=10, unique=True)),
                ('account_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='Product.productcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
